import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/Generated320Widget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedEllipse12Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedGroup8658Widget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedVectorWidget272.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedRectangle4069Widget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedRectangle10Widget6.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedRectangle4070Widget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedMarksFoodandGrillWidget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedGroup6Widget7.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedCHECKOUTWidget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedVectorWidget295.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedGroup5Widget6.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedBasket_alt_3Widget6.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedRectangle4071Widget.dart';
import 'package:flutterapp/figmaapp/generatedcheckoutwidget/generated/GeneratedPataPocherox1Widget.dart';

/* Frame checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.056;
              double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

              double percentHeight = 0.02848575712143928;
              double scaleY = (constraints.maxHeight * percentHeight) / 19.0;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.464,
                    translateY: constraints.maxHeight * 0.9325337331334332,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget272())
              ]);
            }),
          ),
          Positioned(
            left: 4.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedGroup5Widget6(),
          ),
          Positioned(
            left: 0.0,
            top: 45.0,
            right: null,
            bottom: null,
            width: 382.0,
            height: 56.0,
            child: GeneratedRectangle10Widget6(),
          ),
          Positioned(
            left: -4.0,
            top: 585.0,
            right: null,
            bottom: null,
            width: 429.0,
            height: 82.0,
            child: GeneratedGroup6Widget7(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.056;
              double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

              double percentHeight = 0.02848575712143928;
              double scaleY = (constraints.maxHeight * percentHeight) / 19.0;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.464,
                    translateY: constraints.maxHeight * 0.9460269865067467,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget295())
              ]);
            }),
          ),
          Positioned(
            left: 8.0,
            top: 54.0,
            right: null,
            bottom: null,
            width: 44.0,
            height: 39.0,
            child: GeneratedEllipse12Widget5(),
          ),
          Positioned(
            left: 54.0,
            top: 54.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 42.0,
            child: GeneratedBasket_alt_3Widget6(),
          ),
          Positioned(
            left: 97.0,
            top: 58.0,
            right: null,
            bottom: null,
            width: 190.0,
            height: 22.0,
            child: GeneratedCHECKOUTWidget(),
          ),
          Positioned(
            left: 12.0,
            top: 110.0,
            right: null,
            bottom: null,
            width: 351.0,
            height: 124.0,
            child: GeneratedGroup8658Widget(),
          ),
          Positioned(
            left: 12.0,
            top: 243.0,
            right: null,
            bottom: null,
            width: 351.0,
            height: 124.0,
            child: GeneratedRectangle4069Widget(),
          ),
          Positioned(
            left: 12.0,
            top: 376.0,
            right: null,
            bottom: null,
            width: 351.0,
            height: 124.0,
            child: GeneratedRectangle4070Widget(),
          ),
          Positioned(
            left: 258.0,
            top: 527.0,
            right: null,
            bottom: null,
            width: 95.0,
            height: 35.0,
            child: GeneratedRectangle4071Widget(),
          ),
          Positioned(
            left: 27.0,
            top: 124.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 15.0,
            child: GeneratedMarksFoodandGrillWidget(),
          ),
          Positioned(
            left: 135.0,
            top: 160.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 15.0,
            child: GeneratedPataPocherox1Widget(),
          ),
          Positioned(
            left: 252.0,
            top: 209.0,
            right: null,
            bottom: null,
            width: 206.0,
            height: 15.0,
            child: Generated320Widget(),
          )
        ]),
      ),
    ));
  }
}
