import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedCilqrcodeWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedPaywithCashWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedAkariconssearchWidget6.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedScanCodeWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedGroup6Widget9.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedPaywithCreditCardWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedRectangle35Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedWallet_fillWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedVectorWidget346.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedCreditcard_fillWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedBasket_alt_3Widget7.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedPHP218000Widget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedRectangle10Widget8.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedEllipse12Widget7.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedVectorWidget323.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedEtwalletWidget.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedGroup5Widget8.dart';
import 'package:flutterapp/figmaapp/generatedpaymentfororderingwidget/generated/GeneratedRectangle50Widget.dart';

/* Frame Payment for ordering 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentfororderingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -4.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 515.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 142.0,
                child: GeneratedRectangle51Widget(),
              ),
              Positioned(
                left: 93.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 54.0,
                child: GeneratedCreditcard_fillWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 68.0,
                child: GeneratedRectangle50Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget323())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget8(),
              ),
              Positioned(
                left: -4.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 83.0,
                child: GeneratedGroup6Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.47733333333333333,
                        translateY: constraints.maxHeight * 0.9460269865067467,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget346())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 39.0,
                child: GeneratedEllipse12Widget7(),
              ),
              Positioned(
                left: 108.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 27.0,
                child: GeneratedRectangle35Widget5(),
              ),
              Positioned(
                left: 72.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconssearchWidget6(),
              ),
              Positioned(
                left: 96.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 301.0,
                height: 86.0,
                child: GeneratedPHP218000Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 68.0,
                child: GeneratedWallet_fillWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 39.0,
                child: GeneratedEtwalletWidget(),
              ),
              Positioned(
                left: 197.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 100.0,
                child: GeneratedCilqrcodeWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 18.0,
                child: GeneratedPaywithCashWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 18.0,
                child: GeneratedPaywithCreditCardWidget(),
              ),
              Positioned(
                left: 220.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 18.0,
                child: GeneratedScanCodeWidget(),
              ),
              Positioned(
                left: 330.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 42.0,
                child: GeneratedBasket_alt_3Widget7(),
              )
            ]),
      ),
    ));
  }
}
