import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedVectorWidget118.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedAkariconssearchWidget1.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedBasket_alt_3Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedGroup33Widget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedVectorWidget141.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedResultsforBurgerSteakWidget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedGroup32Widget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedBurgersteaknearmeWidget.dart';
import 'package:flutterapp/figmaapp/generatedsearchwidget/generated/GeneratedShowing9ResultforburgerStreaknearbyWidget.dart';

/* Frame Search 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 43.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 140.0,
                child: GeneratedGroup32Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget118())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 41.0,
                child: GeneratedRectangle41Widget1(),
              ),
              Positioned(
                left: -4.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 82.0,
                child: GeneratedGroup6Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4666666666666667,
                        translateY: constraints.maxHeight * 0.9430284857571214,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget141())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 39.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 27.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 13.0,
                child: GeneratedBurgersteaknearmeWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 59.0,
                child: GeneratedResultsforBurgerSteakWidget(),
              ),
              Positioned(
                left: 4.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 28.0,
                child: GeneratedShowing9ResultforburgerStreaknearbyWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 129.0,
                child: GeneratedGroup33Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 136.0,
                child: GeneratedGroup31Widget(),
              ),
              Positioned(
                left: 72.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconssearchWidget1(),
              ),
              Positioned(
                left: 327.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 42.0,
                child: GeneratedBasket_alt_3Widget1(),
              )
            ]),
      ),
    ));
  }
}
