import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedLoginwithWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedSignupWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedWelcometoDinesLIsterWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpagewidget/generated/GeneratedGroup2Widget.dart';

/* Frame LoginPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 621.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 228.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 207.0,
                height: 204.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 89.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 27.0,
                child: GeneratedWelcometoDinesLIsterWidget(),
              ),
              Positioned(
                left: 101.0,
                top: 521.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 40.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 101.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 40.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 134.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 20.0,
                child: GeneratedForgotPasswordWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 20.0,
                child: GeneratedSignupWidget(),
              ),
              Positioned(
                left: 122.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 20.0,
                child: GeneratedLoginwithWidget(),
              ),
              Positioned(
                left: 188.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 18.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 18.0,
                child: GeneratedEllipse4Widget(),
              )
            ]),
      ),
    ));
  }
}
