import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedHindikanakikilalaTarasaBuhaykoWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedEpbackWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedVectorWidget91.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedViewUsersProfileWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedKhongEPaanoandTsinoSotsotRateJollubot35RatingWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/Generated18moreWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedTheirHappyChickenisdeliciousbuttheirgravyisnotthattasty.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedPhotoWidget3.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedIcoutlinepublicWidget1.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedKhongEPaanoWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle69Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedVectorWidget114.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedPhotoWidget4.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedEvaeditoutlineWidget.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/figmaapp/generateduserprofilewidget/generated/Generated2moreWidget.dart';

/* Frame User Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
   
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 22.0,
                  top: 452.0,
                  right: null,
                  bottom: null,
                  width: 333.0,
                  height: 70.0,
                  child: GeneratedGroup30Widget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 537.0,
                  right: null,
                  bottom: null,
                  width: 333.0,
                  height: 70.0,
                  child: GeneratedRectangle33Widget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 571.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedIcoutlinepublicWidget1(),
                ),
                Positioned(
                  left: null,
                  top: 0.0,
                  right: null,
                  bottom: 0.0,
                  width: 277.0,
                  height: null,
                  child: TransformHelper.translate(
                      x: 25.00,
                      y: 0.00,
                      z: 0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double height =
                            constraints.maxHeight * 0.0704647676161919;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: 0,
                              y: constraints.maxHeight * 0.8260869565217391,
                              z: 0,
                              child: Container(
                                height: height,
                                child: GeneratedRectangle34Widget(),
                              ))
                        ]);
                      })),
                ),
                Positioned(
                  left: 151.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 47.0,
                  height: 27.0,
                  child: GeneratedRectangle69Widget(),
                ),
                Positioned(
                  left: 28.0,
                  top: 541.0,
                  right: null,
                  bottom: null,
                  width: 33.0,
                  height: 25.0,
                  child: GeneratedEllipse10Widget(),
                ),
                Positioned(
                  left: 52.0,
                  top: 540.0,
                  right: null,
                  bottom: null,
                  width: 18.0,
                  height: 14.0,
                  child: GeneratedEllipse11Widget(),
                ),
                Positioned(
                  left: 81.0,
                  top: 540.0,
                  right: null,
                  bottom: null,
                  width: 230.0,
                  height: 22.0,
                  child:
                      GeneratedKhongEPaanoandTsinoSotsotRateJollubot35RatingWidget(),
                ),
                Positioned(
                  left: 266.0,
                  top: 581.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 13.0,
                  child: GeneratedGroup27Widget(),
                ),
                Positioned(
                  left: 99.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 47.0,
                  height: 27.0,
                  child: GeneratedRectangle68Widget(),
                ),
                Positioned(
                  left: 89.0,
                  top: 554.0,
                  right: null,
                  bottom: null,
                  width: 168.0,
                  height: 10.0,
                  child:
                      GeneratedTheirHappyChickenisdeliciousbuttheirgravyisnotthattasty(),
                ),
                Positioned(
                  left: 113.0,
                  top: 576.0,
                  right: null,
                  bottom: null,
                  width: 28.0,
                  height: 10.0,
                  child: GeneratedPhotoWidget3(),
                ),
                Positioned(
                  left: 168.0,
                  top: 575.0,
                  right: null,
                  bottom: null,
                  width: 28.0,
                  height: 10.0,
                  child: GeneratedPhotoWidget4(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.056;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 21.0;

                    double percentHeight = 0.02848575712143928;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 19.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.464,
                          translateY:
                              constraints.maxHeight * 0.9325337331334332,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget91())
                    ]);
                  }),
                ),
                Positioned(
                  left: 4.0,
                  top: 1.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedGroup5Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 382.0,
                  height: 127.0,
                  child: GeneratedRectangle10Widget(),
                ),
                Positioned(
                  left: 118.0,
                  top: 108.0,
                  right: null,
                  bottom: null,
                  width: 129.0,
                  height: 123.0,
                  child: GeneratedEllipse5Widget2(),
                ),
                Positioned(
                  left: 104.0,
                  top: 261.0,
                  right: null,
                  bottom: null,
                  width: 194.0,
                  height: 32.0,
                  child: GeneratedKhongEPaanoWidget(),
                ),
                Positioned(
                  left: 67.0,
                  top: 291.0,
                  right: null,
                  bottom: null,
                  width: 245.0,
                  height: 17.0,
                  child: GeneratedHindikanakikilalaTarasaBuhaykoWidget(),
                ),
                Positioned(
                  left: 22.0,
                  top: 380.0,
                  right: null,
                  bottom: null,
                  width: 332.0,
                  height: 56.0,
                  child: GeneratedGroup29Widget(),
                ),
                Positioned(
                  left: 57.0,
                  top: 525.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 15.0,
                  child: Generated18moreWidget(),
                ),
                Positioned(
                  left: 322.0,
                  top: 455.0,
                  right: null,
                  bottom: null,
                  width: 81.0,
                  height: 15.0,
                  child: Generated2moreWidget(),
                ),
                Positioned(
                  left: 3.0,
                  top: 585.0,
                  right: null,
                  bottom: null,
                  width: 422.0,
                  height: 82.0,
                  child: GeneratedGroup6Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 336.0,
                  right: null,
                  bottom: null,
                  width: 447.0,
                  height: 28.0,
                  child: GeneratedGroup28Widget(),
                ),
                Positioned(
                  left: 100.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 212.0,
                  height: 22.0,
                  child: GeneratedViewUsersProfileWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.056;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 21.0;

                    double percentHeight = 0.02848575712143928;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 19.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.47733333333333333,
                          translateY:
                              constraints.maxHeight * 0.9460269865067467,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget114())
                    ]);
                  }),
                ),
                Positioned(
                  left: 9.0,
                  top: 203.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 13.0,
                  child: GeneratedRectangle47Widget(),
                ),
                Positioned(
                  left: 31.0,
                  top: 203.0,
                  right: null,
                  bottom: null,
                  width: 22.0,
                  height: 13.0,
                  child: GeneratedRectangle48Widget(),
                ),
                Positioned(
                  left: 9.0,
                  top: 197.0,
                  right: null,
                  bottom: null,
                  width: 24.0,
                  height: 24.0,
                  child: GeneratedEvaeditoutlineWidget(),
                ),
                Positioned(
                  left: 2.0,
                  top: 45.0,
                  right: null,
                  bottom: null,
                  width: 18.0,
                  height: 15.0,
                  child: GeneratedEpbackWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
