import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedWelcometoDinesLIsterWidget1.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedRectangle4076Widget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedIcoutlinerestaurantWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedRegisterasWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedMdiusercircleWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedRestaurantWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedUserWidget.dart';
import 'package:flutterapp/figmaapp/generatedloginpage2widget/generated/GeneratedRectangle4077Widget.dart';

/* Frame LoginPage2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 41.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 120.0,
                child: GeneratedIcoutlinerestaurantWidget(),
              ),
              Positioned(
                left: 193.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 127.0,
                child: GeneratedMdiusercircleWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup2Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 191.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 125.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 199.0,
                height: 27.0,
                child: GeneratedWelcometoDinesLIsterWidget1(),
              ),
              Positioned(
                left: -9.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 40.0,
                child: GeneratedRectangle4076Widget(),
              ),
              Positioned(
                left: -8.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 391.0,
                height: 46.0,
                child: GeneratedRectangle4077Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 25.0,
                child: GeneratedRegisterasWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 10.0,
                child: GeneratedRestaurantWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 10.0,
                child: GeneratedUserWidget(),
              )
            ]),
      ),
    ));
  }
}
