import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEntervalidemailusernameWidget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEnterpasswordWidget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedGroup24Widget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedWelcometoDinesLIsterWidget2.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedLoginwithWidget1.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedGroup25Widget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/figmaapp/generatedsigninpagewidget/generated/GeneratedRectangle4Widget1.dart';

/* Frame SignInPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignInPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 621.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup2Widget2(),
              ),
              Positioned(
                left: 43.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 288.0,
                height: 27.0,
                child: GeneratedWelcometoDinesLIsterWidget2(),
              ),
              Positioned(
                left: 129.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 153.0,
                height: 24.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 228.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 103.61878967285156,
                top: 110.04020690917969,
                right: null,
                bottom: null,
                width: 192.381103515625,
                height: 219.513427734375,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 129.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 26.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 134.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 15.0,
                child: GeneratedLoginwithWidget1(),
              ),
              Positioned(
                left: 198.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 18.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 222.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 19.0,
                height: 18.0,
                child: GeneratedEllipse4Widget1(),
              ),
              Positioned(
                left: 93.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 32.0,
                child: GeneratedGroup24Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 463.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 32.0,
                child: GeneratedGroup25Widget(),
              ),
              Positioned(
                left: -7.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 19.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: -7.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 19.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 17.0,
                child: GeneratedEntervalidemailusernameWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 17.0,
                child: GeneratedEnterpasswordWidget(),
              )
            ]),
      ),
    ));
  }
}
