import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedGroup28Widget4.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedRectangle35Widget4.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedEllipse12Widget4.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedVectorWidget268.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedMarksBarbequeandGrillWidget8.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedGroup6Widget6.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedJamwriteWidget.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedMarksBarbequeandGrillWidget7.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedMarksBarbequeandGrillWidget9.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedBasket_alt_3Widget5.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedVectorWidget245.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedRectangle71Widget3.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedGroup5Widget5.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedMaterialsymbolscallWidget.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedRectangle10Widget5.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedGroup34Widget3.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedRectangle4075Widget.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedRectangle4043Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedAkariconssearchWidget5.dart';
import 'package:flutterapp/figmaapp/generatedbookwidget2/generated/GeneratedBookWidget3.dart';

/* Frame Book
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 139.0,
            top: 439.0,
            right: null,
            bottom: null,
            width: 43.0,
            height: 38.0,
            child: GeneratedJamwriteWidget(),
          ),
          Positioned(
            left: 71.0,
            top: 350.0,
            right: null,
            bottom: null,
            width: 37.0,
            height: 34.0,
            child: GeneratedRectangle4043Widget1(),
          ),
          Positioned(
            left: 20.0,
            top: 208.0,
            right: null,
            bottom: null,
            width: 338.0,
            height: 219.0,
            child: GeneratedRectangle71Widget3(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.056;
              double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

              double percentHeight = 0.02848575712143928;
              double scaleY = (constraints.maxHeight * percentHeight) / 19.0;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.464,
                    translateY: constraints.maxHeight * 0.9325337331334332,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget245())
              ]);
            }),
          ),
          Positioned(
            left: 4.0,
            top: 1.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedGroup5Widget5(),
          ),
          Positioned(
            left: 0.0,
            top: 45.0,
            right: null,
            bottom: null,
            width: 382.0,
            height: 56.0,
            child: GeneratedRectangle10Widget5(),
          ),
          Positioned(
            left: -4.0,
            top: 585.0,
            right: null,
            bottom: null,
            width: 429.0,
            height: 82.0,
            child: GeneratedGroup6Widget6(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.056;
              double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

              double percentHeight = 0.02848575712143928;
              double scaleY = (constraints.maxHeight * percentHeight) / 19.0;

              return Stack(children: [
                TransformHelper.translateAndScale(
                    translateX: constraints.maxWidth * 0.464,
                    translateY: constraints.maxHeight * 0.9460269865067467,
                    translateZ: 0,
                    scaleX: scaleX,
                    scaleY: scaleY,
                    scaleZ: 1,
                    child: GeneratedVectorWidget268())
              ]);
            }),
          ),
          Positioned(
            left: 16.0,
            top: 54.0,
            right: null,
            bottom: null,
            width: 44.0,
            height: 39.0,
            child: GeneratedEllipse12Widget4(),
          ),
          Positioned(
            left: 108.0,
            top: 64.0,
            right: null,
            bottom: null,
            width: 202.0,
            height: 27.0,
            child: GeneratedRectangle35Widget4(),
          ),
          Positioned(
            left: 118.0,
            top: 72.0,
            right: null,
            bottom: null,
            width: 170.0,
            height: 13.0,
            child: GeneratedMarksBarbequeandGrillWidget7(),
          ),
          Positioned(
            left: 72.0,
            top: 64.0,
            right: null,
            bottom: null,
            width: 24.0,
            height: 24.0,
            child: GeneratedAkariconssearchWidget5(),
          ),
          Positioned(
            left: 76.0,
            top: 147.0,
            right: null,
            bottom: null,
            width: 271.0,
            height: 40.0,
            child: GeneratedMarksBarbequeandGrillWidget8(),
          ),
          Positioned(
            left: 25.0,
            top: 119.0,
            right: null,
            bottom: null,
            width: 388.0,
            height: 28.0,
            child: GeneratedGroup28Widget4(),
          ),
          Positioned(
            left: 128.0,
            top: 185.0,
            right: null,
            bottom: null,
            width: 117.0,
            height: 15.0,
            child: GeneratedGroup34Widget3(),
          ),
          Positioned(
            left: 320.0,
            top: 56.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 42.0,
            child: GeneratedBasket_alt_3Widget5(),
          ),
          Positioned(
            left: 9.0,
            top: 451.0,
            right: null,
            bottom: null,
            width: 271.0,
            height: 40.0,
            child: GeneratedMarksBarbequeandGrillWidget9(),
          ),
          Positioned(
            left: 122.0,
            top: 512.0,
            right: null,
            bottom: null,
            width: 130.0,
            height: 34.0,
            child: GeneratedRectangle4075Widget(),
          ),
          Positioned(
            left: 161.0,
            top: 512.0,
            right: null,
            bottom: null,
            width: 110.0,
            height: 26.0,
            child: GeneratedBookWidget3(),
          ),
          Positioned(
            left: 202.0,
            top: 439.0,
            right: null,
            bottom: null,
            width: 38.0,
            height: 38.0,
            child: GeneratedMaterialsymbolscallWidget(),
          )
        ]),
      ),
    ));
  }
}
