import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8666Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8668Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedRectangle4068Widget1.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup6Widget10.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedFoodnightMarketColonBranchWidget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8662Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup5Widget9.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedRectangle4069Widget1.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedVectorWidget382.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedMarkInasalPorkSisigWidget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8660Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8664Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8661Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedRectangle10Widget9.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8663Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8659Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedSinigangniMangJuanWidget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8667Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedFavoritesWidget11.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedRectangle4074Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedBossUnclesBicolExpressWidget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedGroup8665Widget.dart';
import 'package:flutterapp/figmaapp/generatedfavoritewidget/generated/GeneratedVectorWidget359.dart';

/* Frame favorite
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoriteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
 
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget359())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget9(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget9(),
              ),
              Positioned(
                left: -7.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 39.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: -4.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 82.0,
                child: GeneratedGroup6Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4666666666666667,
                        translateY: constraints.maxHeight * 0.9430284857571214,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget382())
                  ]);
                }),
              ),
              Positioned(
                left: 17.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 29.0,
                child: GeneratedFavoritesWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8659Widget(),
              ),
              Positioned(
                left: 4.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8660Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8661Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8664Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8662Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 239.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 101.0,
                child: GeneratedGroup8663Widget(),
              ),
              Positioned(
                left: 264.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 26.0,
                child: GeneratedRectangle4074Widget(),
              ),
              Positioned(
                left: 292.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 18.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 19.0,
                child: GeneratedSinigangniMangJuanWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 19.0,
                child: GeneratedBossUnclesBicolExpressWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 19.0,
                child: GeneratedFoodnightMarketColonBranchWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 229.0,
                height: 19.0,
                child: GeneratedMarkInasalPorkSisigWidget(),
              ),
              Positioned(
                left: 207.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 24.0,
                child: GeneratedGroup8665Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 24.0,
                child: GeneratedGroup8666Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 24.0,
                child: GeneratedGroup8667Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 24.0,
                child: GeneratedGroup8668Widget(),
              ),
              Positioned(
                left: -4.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 49.0,
                child: GeneratedRectangle4068Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 32.0,
                child: GeneratedRectangle4069Widget1(),
              )
            ]),
      ),
    ));
  }
}
