import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedIconparktwotonelikeWidget1.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/Generated163Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedIconparktwotonelikeWidget3.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedChanEatNGoWidget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/Generated455Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedVectorWidget65.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedVectorWidget40.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup8657Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup13Widget1.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedFoodWidget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedBasket_alt_3Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedLolaTinolahanWidget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/Generated339Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/figmaapp/generatedhomepagewidget/generated/GeneratedPeopleWidget.dart';

/* Frame HomePage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 11.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 109.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 109.0,
                child: GeneratedRectangle54Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 109.0,
                child: GeneratedRectangle56Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 175.00001525878906,
                height: 407.15570068359375,
                child: GeneratedGroup16Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.0721066640218099;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 27.03999900817871;

                  double percentHeight = 0.010884558064290608;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      7.260000228881836;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.23354671223958334,
                        translateY: constraints.maxHeight * 0.9310344827586207,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget40())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06133333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0074962518740629685;
                  double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.25066666666666665,
                        translateY: constraints.maxHeight * 0.9370314842578711,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget65())
                  ]);
                }),
              ),
              Positioned(
                left: 53.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 67.69662857055664,
                height: 16.0,
                child: Generated455Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 67.69662857055664,
                height: 16.0,
                child: Generated339Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 164.90884399414062,
                height: 35.458168029785156,
                child: GeneratedChanEatNGoWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 36.0,
                child: GeneratedIconparktwotonelikeWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 162.90884399414062,
                height: 103.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 50.0,
                child: GeneratedGroup13Widget1(),
              ),
              Positioned(
                left: 329.0,
                top: 49.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 42.0,
                child: GeneratedBasket_alt_3Widget(),
              ),
              Positioned(
                left: -5.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 381.0,
                height: 88.0,
                child: GeneratedGroup19Widget(),
              ),
              Positioned(
                left: 193.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 13.0,
                child: GeneratedPeopleWidget(),
              ),
              Positioned(
                left: 104.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 13.0,
                child: GeneratedFoodWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 422.0,
                height: 82.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 157.0,
                child: GeneratedRectangle61Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 27.527128219604492,
                height: 35.426292419433594,
                child: GeneratedIconparktwotonelikeWidget3(),
              ),
              Positioned(
                left: 197.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 22.0,
                child: GeneratedLolaTinolahanWidget(),
              ),
              Positioned(
                left: 238.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 25.0,
                child: Generated163Widget(),
              ),
              Positioned(
                left: 193.9942626953125,
                top: 188.0,
                right: null,
                bottom: null,
                width: 173.0056915283203,
                height: 247.0,
                child: GeneratedGroup20Widget(),
              ),
              Positioned(
                left: 300.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 61.93815231323242,
                height: 15.155709266662598,
                child: GeneratedGroup8657Widget(),
              )
            ]),
      ),
    ));
  }
}
