import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedDirectionWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle35Widget3.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedBookWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedCallWidget2.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle10Widget4.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedBxfoodmenuWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedEllipse12Widget3.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedBxsdirectionrightWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedGroup5Widget4.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedGroup28Widget3.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle79Widget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedMingallanillaCebuWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle4041Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedOpenMonSunday900am700pmWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedD1Widget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedGroup6Widget5.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedVectorWidget212.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedFile_dock_search_fillWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedBxsphoneWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedMarksBarbequeandGrillWidget5.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedBasket_alt_3Widget4.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedVectorWidget207.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedFoodMenuWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle71Widget2.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedMedicaliconrestaurantWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedOpenmojimanstandingWidget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedMarksBarbequeandGrillWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle4044Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle4045Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/Generated1450Widget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle4043Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedAsof1000amOct32022Widget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedVectorWidget235.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedGroup34Widget2.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedVector340Widget.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedMarksBarbequeandGrillWidget4.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle78Widget1.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedAkariconssearchWidget4.dart';
import 'package:flutterapp/figmaapp/generatedmapwidget/generated/GeneratedRectangle4042Widget.dart';

/* Frame Map
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMapWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 71.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 34.0,
                child: GeneratedRectangle4043Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 444.0,
                child: GeneratedRectangle4041Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 119.0,
                child: GeneratedRectangle79Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 20.0,
                child: GeneratedOpenMonSunday900am700pmWidget1(),
              ),
              Positioned(
                left: 54.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedMingallanillaCebuWidget1(),
              ),
              Positioned(
                left: 53.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxsdirectionrightWidget1(),
              ),
              Positioned(
                left: 122.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxsphoneWidget1(),
              ),
              Positioned(
                left: 56.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedDirectionWidget1(),
              ),
              Positioned(
                left: 98.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedBookWidget1(),
              ),
              Positioned(
                left: 166.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 19.0,
                child: GeneratedFoodMenuWidget1(),
              ),
              Positioned(
                left: 131.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 49.000244140625,
                height: 38.814697265625,
                child: GeneratedCallWidget2(),
              ),
              Positioned(
                left: 89.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedMedicaliconrestaurantWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.096;
                  double scaleX = (constraints.maxWidth * percentWidth) / 36.0;

                  double percentHeight = 0.05247376311844078;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 35.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8,
                        translateY: constraints.maxHeight * 0.8350824587706147,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget207())
                  ]);
                }),
              ),
              Positioned(
                left: 282.0,
                top: 534.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 13.0,
                child: GeneratedRectangle78Widget1(),
              ),
              Positioned(
                left: 290.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 28.0,
                child: Generated1450Widget1(),
              ),
              Positioned(
                left: 242.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 16.0,
                child: GeneratedAsof1000amOct32022Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 59.0,
                child: GeneratedD1Widget1(),
              ),
              Positioned(
                left: 163.0,
                top: 553.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxfoodmenuWidget1(),
              ),
              Positioned(
                left: 164.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFile_dock_search_fillWidget1(),
              ),
              Positioned(
                left: -3.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 100.0,
                child: GeneratedRectangle71Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget212())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget4(),
              ),
              Positioned(
                left: -4.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 82.0,
                child: GeneratedGroup6Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9460269865067467,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget235())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 39.0,
                child: GeneratedEllipse12Widget3(),
              ),
              Positioned(
                left: 108.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 27.0,
                child: GeneratedRectangle35Widget3(),
              ),
              Positioned(
                left: 118.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 13.0,
                child: GeneratedMarksBarbequeandGrillWidget4(),
              ),
              Positioned(
                left: 72.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconssearchWidget4(),
              ),
              Positioned(
                left: 75.0,
                top: 165.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 40.0,
                child: GeneratedMarksBarbequeandGrillWidget5(),
              ),
              Positioned(
                left: 27.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 28.0,
                child: GeneratedGroup28Widget3(),
              ),
              Positioned(
                left: 135.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 15.0,
                child: GeneratedGroup34Widget2(),
              ),
              Positioned(
                left: 320.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 42.0,
                child: GeneratedBasket_alt_3Widget4(),
              ),
              Positioned(
                left: 78.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 50.0,
                child: GeneratedRectangle4044Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 70.0,
                child: GeneratedRectangle4045Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 121.0,
                child: GeneratedVector340Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 124.0,
                child: GeneratedRectangle4042Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 40.0,
                child: GeneratedMarksBarbequeandGrillWidget6(),
              ),
              Positioned(
                left: 120.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 9.0,
                child: GeneratedGroup35Widget(),
              ),
              Positioned(
                left: 177.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 31.0,
                child: GeneratedOpenmojimanstandingWidget(),
              )
            ]),
      ),
    ));
  }
}
