import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedFoodMenuWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedDirectionWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedGroup28Widget1.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedMarksBarbequeandGrillWidget1.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBxfoodmenuWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedCallWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle75Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedVectorWidget144.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle77Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle72Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedMarksBarbequeandGrillWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedVectorWidget172.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle78Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBasket_alt_3Widget2.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle79Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedPorkSisig99Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedFile_dock_search_fillWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedFollowWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBxsdirectionrightWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBookWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBestSellersWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedVectorWidget167.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedPaasManok1pc99Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedAsof1000amOct32022Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedMingallanillaCebuWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedGroup5Widget2.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedGroup6Widget3.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle74Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedEllipse12Widget1.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedBxsphoneWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle76Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedOpenMonSunday900am700pmWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/Generated1450Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedDineinTakeoutWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedD1Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedMarksPorkandBBQ3pcs119Widget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedMedicaliconrestaurantWidget.dart';
import 'package:flutterapp/figmaapp/generatedrestautantprofwidget/generated/GeneratedAkariconssearchWidget2.dart';

/* Frame Restautant prof
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRestautantprofWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
 
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 19.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 344.0,
                height: 119.0,
                child: GeneratedRectangle79Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 20.0,
                child: GeneratedRectangle74Widget(),
              ),
              Positioned(
                left: -50.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 432.0,
                height: 163.0,
                child: GeneratedRectangle72Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget144())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget2(),
              ),
              Positioned(
                left: -4.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 82.0,
                child: GeneratedGroup6Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9460269865067467,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget167())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 39.0,
                child: GeneratedEllipse12Widget1(),
              ),
              Positioned(
                left: 108.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 27.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 118.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 13.0,
                child: GeneratedMarksBarbequeandGrillWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAkariconssearchWidget2(),
              ),
              Positioned(
                left: 54.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 168.0,
                child: GeneratedRectangle71Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 271.0,
                height: 40.0,
                child: GeneratedMarksBarbequeandGrillWidget1(),
              ),
              Positioned(
                left: 53.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 12.0,
                child: GeneratedDineinTakeoutWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 20.0,
                child: GeneratedOpenMonSunday900am700pmWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedMingallanillaCebuWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 20.0,
                child: GeneratedBestSellersWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 26.0,
                child: GeneratedMarksPorkandBBQ3pcs119Widget(),
              ),
              Positioned(
                left: 148.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 57.0,
                child: GeneratedPaasManok1pc99Widget(),
              ),
              Positioned(
                left: 236.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 57.0,
                child: GeneratedPorkSisig99Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 67.0,
                child: GeneratedRectangle75Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 67.0,
                child: GeneratedRectangle76Widget(),
              ),
              Positioned(
                left: 236.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 66.0,
                child: GeneratedRectangle77Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxsdirectionrightWidget(),
              ),
              Positioned(
                left: 122.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxsphoneWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedDirectionWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedBookWidget(),
              ),
              Positioned(
                left: 166.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 19.0,
                child: GeneratedFoodMenuWidget(),
              ),
              Positioned(
                left: 131.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 49.000244140625,
                height: 38.814697265625,
                child: GeneratedCallWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 20.0,
                child: GeneratedMedicaliconrestaurantWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.096;
                  double scaleX = (constraints.maxWidth * percentWidth) / 36.0;

                  double percentHeight = 0.05247376311844078;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 35.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8,
                        translateY: constraints.maxHeight * 0.6371814092953523,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget172())
                  ]);
                }),
              ),
              Positioned(
                left: 282.0,
                top: 402.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 13.0,
                child: GeneratedRectangle78Widget(),
              ),
              Positioned(
                left: 290.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 28.0,
                child: Generated1450Widget(),
              ),
              Positioned(
                left: 242.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 16.0,
                child: GeneratedAsof1000amOct32022Widget(),
              ),
              Positioned(
                left: 174.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 19.0,
                child: GeneratedFollowWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 28.0,
                child: GeneratedGroup28Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 59.0,
                child: GeneratedD1Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 15.0,
                child: GeneratedGroup34Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 421.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedBxfoodmenuWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 42.0,
                child: GeneratedBasket_alt_3Widget2(),
              ),
              Positioned(
                left: 164.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedFile_dock_search_fillWidget(),
              )
            ]),
      ),
    ));
  }
}
