import 'package:flutter/material.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle10Widget7.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse175Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse172Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4067Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4046Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4059Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4062Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse173Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse174Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedVectorWidget297.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4048Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4056Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedGroup6Widget8.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4063Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse12Widget6.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse169Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4057Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedGroup5Widget7.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4065Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4058Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4049Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse171Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4060Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4061Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4055Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedVectorWidget321.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4064Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedEllipse170Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedMessagesWidget10.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4047Widget.dart';
import 'package:flutterapp/figmaapp/generatedmessageswidget8/generated/GeneratedRectangle4066Widget.dart';

/* Frame Messages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessagesWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,

            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 148.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 466.0,
                child: GeneratedRectangle4048Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 99.0,
                child: GeneratedRectangle4055Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9325337331334332,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget297())
                  ]);
                }),
              ),
              Positioned(
                left: 4.0,
                top: 1.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedGroup5Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 45.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 56.0,
                child: GeneratedRectangle10Widget7(),
              ),
              Positioned(
                left: -4.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 602.0,
                child: GeneratedGroup6Widget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.056;
                  double scaleX = (constraints.maxWidth * percentWidth) / 21.0;

                  double percentHeight = 0.02848575712143928;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.464,
                        translateY: constraints.maxHeight * 0.9460269865067467,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget321())
                  ]);
                }),
              ),
              Positioned(
                left: 8.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 39.0,
                child: GeneratedEllipse12Widget6(),
              ),
              Positioned(
                left: 97.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 25.0,
                child: GeneratedMessagesWidget10(),
              ),
              Positioned(
                left: -5.0,
                top: 101.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 49.0,
                child: GeneratedRectangle4046Widget(),
              ),
              Positioned(
                left: 4.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 358.0,
                height: 32.0,
                child: GeneratedRectangle4047Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 22.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4049Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4056Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 219.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4057Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4058Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4059Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 74.0,
                child: GeneratedRectangle4060Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle4061Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse169Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse170Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse171Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 377.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse172Widget(),
              ),
              Positioned(
                left: 9.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse173Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedEllipse174Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4062Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4063Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4064Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4065Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4066Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 458.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 45.0,
                child: GeneratedRectangle4067Widget(),
              ),
              Positioned(
                left: 352.0,
                top: 203.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 13.0,
                child: GeneratedEllipse175Widget(),
              )
            ]),
      ),
    ));
  }
}
